### PR TITLE
Add Go Report Card to README

### PR DESCRIPTION
**Pull request by naltun**
I came across your post on Reddit and you asked for feedback. Having a 'Go Report Card' helps you keep track of any potential formatting improvements to make. If you click on the shield, it will take you to the report where it will highlight where in your code Golang formatting issues exist.

If you don't want the report card, no harm done. Good luck. :)

### CODE REVIEW

**Comment by Shadowbeetle** [comment]
Good idea, thanks!

**Comment by naltun** [comment]
BTW, _awesome_ project! 👌

**Comment by Shadowbeetle** [comment]
Thanks! :) 
Could you help me understand the data races I get when I run the tests as well?

**Comment by naltun** [comment]
Can you point me to any specific examples or provide any additional info? I'd love to help.

**Comment by naltun** [comment]
Sure, I'd love to. How are you running tests? What additional info can you provide?

**Comment by Shadowbeetle** [comment]
I only have tests for `github.com/Shadowbeetle/skbl/backlight`. When I run `go test -race github.com/Shadowbeetle/skbl/backlight` I get tons of races, but to be honest I have no idea what to make of them. Most of them are either written or read by one of my goroutines, but also accessed by `testing.go` or `strings/reader.go` and it doesn't really help me figuring out what causes the race condition, or how to fix it.

**Comment by naltun** [comment]
@Shadowbeetle I've opened up a new issue [here](https://github.com/Shadowbeetle/skbl/issues/3).

**Comment by Shadowbeetle** [comment]
Thanks! :)

**Pull request merged**
